# Generated by Django 4.1.3 on 2022-12-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('passwd', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=50, verbose_name='이메일')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='전화번호')),
                ('depart', models.CharField(choices=[('선택안함', '선택안함'), ('영업부', '영업부'), ('관리부', '관리부'), ('경리부', '경리부'), ('개발부', '개발부')], max_length=10, verbose_name='부서')),
                ('logtime', models.DateTimeField(auto_now_add=True, verbose_name='입사일')),
            ],
        ),
    ]
