# Generated by Django 4.1.3 on 2022-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='글번호')),
                ('writer', models.CharField(max_length=50, verbose_name='작성자')),
                ('subject', models.CharField(max_length=300, verbose_name='글제목')),
                ('passwd', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('content', models.TextField(verbose_name='글내용')),
                ('readcount', models.IntegerField(default=0, verbose_name='조회수')),
                ('ref', models.IntegerField(verbose_name='그룹화아이디')),
                ('restep', models.IntegerField(verbose_name='글순서')),
                ('relevel', models.IntegerField(verbose_name='글레벨')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('ip', models.CharField(max_length=30, verbose_name='아이피')),
            ],
        ),
    ]
